" Global

set nocompatible
set encoding=UTF-8
set fileencodings=utf-8,latin1
set termencoding=utf-8
set ffs=unix,dos,mac


set number " change screen resolution
set history=999
set undolevels=999
set autoread
set nobackup
set softtabstop=2
set shiftwidth=2
set smarttab
set nowritebackup
set tabstop=2
set gdefault
set magic
set hlsearch
set incsearch
set ignorecase smartcase
set backspace=indent,eol,start
set esckeys
set nostartofline
set timeoutlen=500
set ttimeoutlen=100
set title
set splitbelow splitright
set scrolloff=7
set sidescroll=1
set hls
set novb
set tabstop=2
set showtabline=2
set cursorline
set secure
set showmode
set showmatch
set nohidden
set ttyfast
set noerrorbells
set report=0
set nowb
set noswapfile
set wildmenu
set wildchar=<TAB>
set wildmode=list:longest
set wildignore+=*/.git/*,*/.svn/*,*/node_modules/*
set wildignore+=*.DS_STORE,*.db,node_modules/**,*.jpg,*.png,*.jpeg,*.gif
"set diffopt=filter
"set# diffopt=iwhite
set foldmethod=manual
set foldnestmax=3
set nofoldenable
set copyindent
set softtabstop=2
set smarttab
set expandtab
set visualbell
set wrap
set textwidth=120
set formatoptions=qrn1
set formatoptions-=o
set nomodeline
set pastetoggle=<leader>p
set selection=inclusive
set t_vb=
set tm=500
set showcmd
set matchtime=2

" next tab
nnoremap <C-Tab> :tabn<CR>

" advanced stuff for file handling
augroup mm_buf_cmds
        autocmd!

        autocmd bufwritepost .vimrc source %
        au WinLeave,InsertEnter * set nocul
        au WinEnter,InsertLeave * set cul
        autocmd bufNewFile,BufRead *.json setf json
augroup EN

" plugins 
call  plug#begin('~/.vim/plugged')
" NERD
Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
" NEOClide/COC
" Only if NodeJS 
"Plug 'neoclide/coc.nvim', {'branch':'master','do':'yarm install --frozen-lockfile'}
call plug#end()

" Configure NERDTree
nnoremap <silent> <C-t> :NERDTreeToggle<CR>

" Disable auto-comments
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o



